version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
  api:
    image: api_service
    restart: always
    ports:
      - 5000:5000
    container_name: api
    depends_on:
      - mongodb
  app:
    image: app
    container_name: app
    ports:
      - 5002:5002